categories:
  - title: "🚀 Features"
    labels:
      - "feature"
      - "enhancement"
      - "feat"
  - title: "🐛 Fixes"
    labels:
      - "bugfix"
      - "hotfix"
      - "fix"
      - "bug"
  - title: "🌱 Updates"
    labels:
      - "dependencies"
      - "update"
      - "dependency-update"
exclude-labels:
  - "skip-changelog"
  - "invalid"
template: |
  ## 📢 What's changed?
  $CHANGES
  ## 🔙 Previous
  $PREVIOUS_TAG
