name: release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Bump version
        uses: phips28/gh-action-bump-version@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          commit-message: "ci: bumps version to {{version}} [skip ci]"
          default: minor

      - name: Extract latest version
        run: echo VERSION=$(git describe --tags --abbrev=0) >> $GITHUB_ENV

      - name: Publish release notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
          name: "${{ env.VERSION }}"
          tag: "${{ env.VERSION }}"
          version: "${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
