name: release

on:
  workflow_dispatch:
    inputs:
      version_type:
        description: "Select version bump type"
        required: true
        default: "minor"
        type: choice
        options:
          - major
          - minor
          - patch

jobs:
  release:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Git user
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

      - name: Extract latest version
        run: echo VERSION=$(git describe --tags --abbrev=0 2>/dev/null || echo "v0.1.0") >> $GITHUB_ENV

      - name: Bump version
        run: |
          LATEST_TAG="${{ env.VERSION }}"
          MAJOR=$(echo "$LATEST_TAG" | cut -d. -f1 | tr -d 'v')
          MINOR=$(echo "$LATEST_TAG" | cut -d. -f2)
          PATCH=$(echo "$LATEST_TAG" | cut -d. -f3)

          if [ "${{ inputs.version_type }}" = "major" ]; then
            NEW_VERSION="v$((MAJOR + 1)).0.0"
          elif [ "${{ inputs.version_type }}" = "minor" ]; then
            NEW_VERSION="v$MAJOR.$((MINOR + 1)).0"
          else
            NEW_VERSION="v$MAJOR.$MINOR.$((PATCH + 1))"
          fi

          echo "New version: $NEW_VERSION"
          echo "$NEW_VERSION" > VERSION
          echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV

      - name: Commit and tag new version
        env:
          PAT: ${{ secrets.GH_PAT }} # Use PAT authentication
        run: |
          git add VERSION
          git commit -m "ci: bump version to ${{ env.VERSION }}"

          git tag ${{ env.VERSION }}

          # Authenticate using PAT
          git remote set-url origin https://x-access-token:${{ env.PAT }}@github.com/${{ github.repository }}.git

          # Push the commit and the tag explicitly
          git push origin main  # Change 'main' to your default branch if different
          git push origin ${{ env.VERSION }}  # Push the tag

      - name: Publish Release Notes
        uses: release-drafter/release-drafter@v5
        with:
          config-name: release-drafter.yml
          publish: true
          name: "${{ env.VERSION }}"
          tag: "${{ env.VERSION }}"
          version: "${{ env.VERSION }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
